name: Jumat Berkah

on:
  schedule:
    - cron: '0 2 * * 5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Commits
        run: |
          git config --local user.email "onymcraft@gmail.com"
          git config --local user.name "ClaireFearless"

          for i in {1..15}
          do
            echo "Update Jumat ke-$i: $(date)" >> jumat_log.txt
            
            git add .
            git commit -m "chore: friday update $i"

            sleep 2
          done

      - name: Push Changes
        run: |
          git push
