name: Jumat Berkah

on:
  schedule:
    - cron: '0 2 * * 5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 15 commits
        run: |
          git config --local user.email "onymcraft@gmail.com"
          git config --local user.name "ClaireFearless"

          for i in {1..15}
          do
            echo "Update Jumat ke-$i $(date +%s)" >> jumat_log.txt

            git add jumat_log.txt
            git commit -m "commit nomor $i"

            sleep 3
          done

      - name: Push
        run: git push
